name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull-request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn run eslint
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e
          start: yarn run start-prod
          wait-on: http://localhost:5000
          browser: chrome
      - name: deploy-to-heroku
        if: ${{ github.event_name == "push"}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: infinite-ridge-75598
          heroku_email: maitran.ln99@gmail.com
          healthcheck: https://infinite-ridge-75598.herokuapp.com/health
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
