name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: yarn install
        run: yarn install
      - name: lint
        run: yarn run eslint
      - name: build
        run: yarn run build
      - name: test
        run: yarn run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn run test:e2e
          start: yarn run start-prod
          wait-on: http://localhost:5000
          browser: chrome
      - name: deploy-to-heroku
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: infinite-ridge-75598
          heroku_email: maitran.ln99@gmail.com
          healthcheck: https://infinite-ridge-75598.herokuapp.com/health
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  tagging_pipeline:
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message),'#skip')}}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
  notifications_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Indicate error if the build fails
        if: ${{ job.status != 'success'}}
        uses: 8398a7/action-slack@v3.12.0
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Indicate success if a new version is deployed
        if: ${{ job.status == 'success'}}
        uses: 8398a7/action-slack@v3.12.0
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
